//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_line
    {
        public int id { get; set; }
        public Nullable<int> count { get; set; }
        public string cost { get; set; }
    
        public virtual OrderC OrderC { get; set; }
        public virtual Product Product { get; set; }
    }
}
